- hosts: localhost
  vars:
    source_key: "./.ssh/id_personal"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_personal"
    personal: "{{ lookup('env', 'HOME') }}/personal"
    work: "{{ lookup('env', 'HOME') }}/org"
    source_key_work: "./.ssh/id_a2sv"
    dest_key_work: "{{ lookup('env', 'HOME') }}/.ssh/id_a2sv"
    ssh_config_source: "./.ssh/config"
    ssh_config_dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
  tasks:
    - import_tasks: tasks/ssh-setup.yml
    - import_tasks: tasks/git-setup.yml
