- name: Install fnm Node Manager
  shell: curl -fsSL https://fnm.vercel.app/install | bash 
  tags:
  - install
  - node
- name: Install Nodejs
  shell: fnm install --lts
  tags:
    - install
    - node
- name: Install pnpm
  shell: curl -fsSL https://get.pnpm.io/install.sh | sh -
  tags:
    - install
    - node
